2025-06-22 02:32:22,305 - __main__ - INFO - 서버에 연결되었습니다: localhost:8888
2025-06-22 02:32:22,307 - __main__ - ERROR - 업로드 시도 1 실패: [Errno 54] Connection reset by peer
2025-06-22 02:32:23,309 - __main__ - ERROR - 업로드 시도 2 실패: [Errno 54] Connection reset by peer
2025-06-22 02:32:24,312 - asyncio - WARNING - socket.send() raised exception.
2025-06-22 02:32:24,312 - asyncio - WARNING - socket.send() raised exception.
2025-06-22 02:32:24,313 - __main__ - ERROR - 업로드 시도 3 실패: [Errno 54] Connection reset by peer
2025-06-22 02:32:25,316 - asyncio - WARNING - socket.send() raised exception.
2025-06-22 02:32:25,317 - asyncio - WARNING - socket.send() raised exception.
2025-06-22 02:32:25,317 - __main__ - ERROR - 업로드 시도 4 실패: [Errno 54] Connection reset by peer
2025-06-22 02:32:25,317 - asyncio - WARNING - socket.send() raised exception.
2025-06-22 02:32:25,318 - asyncio - WARNING - socket.send() raised exception.
2025-06-22 02:33:11,434 - __main__ - INFO - 파일 전송 서버가 ('127.0.0.1', 8888)에서 시작되었습니다.
2025-06-22 02:33:38,580 - __main__ - INFO - 서버에 연결되었습니다: localhost:8888
2025-06-22 02:33:38,580 - __main__ - INFO - 클라이언트 연결: ('::1', 63592, 0, 0)
2025-06-22 02:33:38,581 - __main__ - ERROR - 업로드 실패: 업로드 오류: [Errno 2] No such file or directory: ''
2025-06-22 02:35:01,687 - __main__ - INFO - 서버 연결을 종료했습니다.
2025-06-22 02:35:01,687 - __main__ - ERROR - 메시지 수신 오류: 190 bytes read on a total of 682962941 expected bytes
2025-06-22 02:35:01,687 - __main__ - INFO - 클라이언트 연결 종료: ('::1', 63592, 0, 0)
2025-06-22 02:36:24,377 - __main__ - INFO - 서버가 중지되었습니다.
2025-06-22 02:36:24,377 - __main__ - INFO - 서버에 연결되었습니다: localhost:8888
2025-06-22 02:36:24,378 - __main__ - ERROR - 업로드 시도 1 실패: [Errno 54] Connection reset by peer
2025-06-22 02:36:25,388 - __main__ - ERROR - 업로드 시도 2 실패: [Errno 54] Connection reset by peer
2025-06-22 02:36:26,389 - asyncio - WARNING - socket.send() raised exception.
2025-06-22 02:36:26,390 - asyncio - WARNING - socket.send() raised exception.
2025-06-22 02:36:26,390 - __main__ - ERROR - 업로드 시도 3 실패: [Errno 54] Connection reset by peer
2025-06-22 02:36:27,393 - asyncio - WARNING - socket.send() raised exception.
2025-06-22 02:36:27,393 - asyncio - WARNING - socket.send() raised exception.
2025-06-22 02:36:27,393 - __main__ - ERROR - 업로드 시도 4 실패: [Errno 54] Connection reset by peer
2025-06-22 02:36:27,393 - asyncio - WARNING - socket.send() raised exception.
2025-06-22 02:36:27,393 - asyncio - WARNING - socket.send() raised exception.
2025-06-22 02:38:12,728 - __main__ - ERROR - 다운로드 실패: 파일을 찾을 수 없습니다
2025-06-22 02:38:12,729 - __main__ - ERROR - 다운로드 실패: 파일을 찾을 수 없습니다
2025-06-22 02:38:12,729 - __main__ - ERROR - 다운로드 실패: 파일을 찾을 수 없습니다
2025-06-22 02:38:12,729 - __main__ - ERROR - 다운로드 실패: 파일을 찾을 수 없습니다
